/**
 * Verifies the TS port (likenessModel.ts) reproduces the Python reference implementation's
 * numbers exactly (within floating-point tolerance) for real extracted India field data. The
 * fixture (sunflowerLikenessFixture.json) is generated by
 * training/sunflower/verify_likeness_model_export.py from the SAME exported JSON model artifact
 * this module loads — so this checks "does the TS math match", not "is the model any good".
 *
 * Run: cd server && npx tsx scripts/verifySunflowerLikeness.ts
 */
import { readFileSync } from 'node:fs'
import { fileURLToPath } from 'node:url'
import { scoreSunflowerLikeness } from '../src/services/agricultural/sunflower/likenessModel.js'
import type { SunflowerFeatures } from '../src/services/agricultural/sunflower/types.js'

interface Fixture {
  field_id: string
  crop_label: string
  raw_spectral: {
    ndviMean: number | null
    ndviPeakValue: number | null
    ndreMean: number | null
    ndrePeakValue: number | null
    ndwiMean: number | null
    ndwiPeakValue: number | null
    yellowIndexMean: number | null
    yellowIndexPeakValue: number | null
    observationCount: number
  }
  expected: { mahalanobisLikeness: number; knnLikeness: number; likeness: number; band: string }
}

const FIXTURE_PATH = fileURLToPath(new URL('./sunflowerLikenessFixture.json', import.meta.url))
const fixtures: Fixture[] = JSON.parse(readFileSync(FIXTURE_PATH, 'utf-8'))

const TOLERANCE = 1e-6
let passed = 0
let failed = 0

function check(label: string, actual: number, expected: number): void {
  const ok = Math.abs(actual - expected) < TOLERANCE
  console.log(`${ok ? 'PASS' : 'FAIL'} ${label}: expected=${expected} actual=${actual}`)
  if (ok) passed++
  else failed++
}

for (const fixture of fixtures) {
  const spectral: SunflowerFeatures['spectral'] = {
    ndviMean: fixture.raw_spectral.ndviMean,
    ndviSlope: null,
    ndviPeakValue: fixture.raw_spectral.ndviPeakValue,
    ndreMean: fixture.raw_spectral.ndreMean,
    ndreSlope: null,
    ndrePeakValue: fixture.raw_spectral.ndrePeakValue,
    ndwiMean: fixture.raw_spectral.ndwiMean,
    ndwiPeakValue: fixture.raw_spectral.ndwiPeakValue,
    yellowIndexMean: fixture.raw_spectral.yellowIndexMean,
    yellowIndexSlope: null,
    yellowIndexPeakValue: fixture.raw_spectral.yellowIndexPeakValue,
    observationCount: fixture.raw_spectral.observationCount,
  }

  const result = scoreSunflowerLikeness(spectral)
  console.log(`\n=== ${fixture.field_id} (${fixture.crop_label}) ===`)
  if ('available' in result && result.available === false) {
    console.log(`FAIL ${fixture.field_id}: got available:false (${result.reason}), expected a real score`)
    failed++
    continue
  }
  check('mahalanobisLikeness', result.mahalanobisLikeness, fixture.expected.mahalanobisLikeness)
  check('knnLikeness', result.knnLikeness, fixture.expected.knnLikeness)
  check('likeness', result.likeness, fixture.expected.likeness)
  const bandOk = result.band === fixture.expected.band
  console.log(`${bandOk ? 'PASS' : 'FAIL'} band: expected=${fixture.expected.band} actual=${result.band}`)
  if (bandOk) passed++
  else failed++
}

console.log(`\n${passed} passed, ${failed} failed`)
process.exit(failed > 0 ? 1 : 0)
